habit_notes/urls.py
from django.urls import path
from . import views

app_name = 'habit_notes'

urlpatterns = [
    path('', views.all_notes_view, name='all_notes'),
    path('habit/<int:habit_id>/notes/add/', views.add_note, name='add_note'),
    path('note/<int:note_id>/delete/', views.delete_note, name='delete_note'), 
]

habitflow/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('habits/', include('habits.urls', namespace='habits')),
    path('notes/', include('habit_notes.urls', namespace='habit_notes')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

habits/urls.py
# habits/urls.py
from django.urls import path
from . import views

app_name = 'habits'

urlpatterns = [
    path('create/', views.create_habit, name='create_habit'),
    path('your_habits/', views.habit_list, name='habit_list'),
    path('tracker/<int:habit_id>/', views.habit_tracker_view, name='habit_tracker'),
    path('tracker/<int:habit_id>/toggle/', views.toggle_completion, name='toggle_completion'),
    path('delete/<int:habit_id>/', views.delete_habit, name='delete_habit'),
]

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name= 'index'),
    path('about/', views.about, name= 'about'),
    path('about_us/', views.about_us, name= 'about_us'),
    path('settings/', views.settings, name= 'settings'),
    path('main-after-registration/', views.main_after_registration, name='main_after_registration'),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name= 'login'),
    path('registration/', views.registration, name= 'registration'),
    path('profile/', views.profile, name= 'profile'),
    path(
        'password_reset/',
        auth_views.PasswordResetView.as_view(
            template_name='users/password_reset_form.html',
            email_template_name='users/password_reset_email.html',
            subject_template_name='users/password_reset_subject.txt',
            success_url='done/'
        ),
        name='password_reset'
    ),
    
    path(
        'password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url='/users/reset/done/'
        ),
        name='password_reset_confirm'
    ),

    path(
        'reset/done/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),

    path('logout/', views.logout, name= 'logout'),
    path('delete_account/', views.delete_account, name='delete_account'),
]

habit_notes/models.py
from django.db import models
from habits.models import Habit
from django.utils import timezone

class HabitNote(models.Model):
    MOOD_CHOICES = [
        ('happy', '😊 Happy'),
        ('neutral', '😐 Neutral'),
        ('sad', '😞 Sad'),
        ('angry', '😠 Angry'),
        ('tired', '😩 Tired'),
    ]

    habit = models.ForeignKey(
        Habit,
        on_delete=models.CASCADE,
        related_name='notes'
    )
    
    date = models.DateField(default=timezone.now)
    note = models.TextField(blank=True)
    photo = models.ImageField(upload_to='habit_notes_photos/', blank=True, null=True)
    mood = models.CharField(max_length=10, choices=MOOD_CHOICES, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-date']

    def __str__(self):
        return f'Note for {self.habit.name} on {self.date}'

habits/models.py
from django.db import models
from django.conf import settings

class Habit(models.Model):
    GOOD_OR_BAD_CHOICES = (
        ('good', 'Good'),
        ('bad', 'Bad'),
    )

    FREQUENCY_CHOICES = (
        ('daily', 'Daily'),
        ('weekly', 'Weekly'),
        ('biweekly', 'Every 2 Weeks'),
        ('monthly', 'Monthly'),
        ('semiannual', 'Every 6 Months'),
        ('yearly', 'Yearly'),
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='habits'
    )
    
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    category = models.CharField(max_length=4, choices=GOOD_OR_BAD_CHOICES)
    frequency = models.CharField(max_length=10, choices=FREQUENCY_CHOICES)
    end_date = models.DateField()
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f'{self.name} ({self.category})'
    

class HabitCompletion(models.Model):
    habit = models.ForeignKey(Habit, on_delete=models.CASCADE, related_name='completions')
    date = models.DateField()
    completed = models.BooleanField(default=False)

    class Meta:
        unique_together = ('habit', 'date')
    
    def __str__(self):
        return f'Habit: {self.habit.name} | {self.date} | Completed: {self.completed}'


        

habit_notes/forms.py
from django import forms
from .models import HabitNote

class HabitNoteForm(forms.ModelForm):
    class Meta:
        model = HabitNote
        fields = ['date', 'note', 'photo', 'mood']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'mood': forms.Select(),
            'note': forms.Textarea(attrs={'rows': 4}),
        }

habit_notes/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import HabitNote
from habits.models import Habit
from .forms import HabitNoteForm


def all_notes_view(request):
    habits = Habit.objects.filter(user=request.user).prefetch_related('notes')
    if(habits): return render(request, 'habit_notes/all_notes.html', {'habits': habits})
    else: return render(request, 'habits/habitat_without_value.html')
 
def add_note(request, habit_id):
    habit = get_object_or_404(Habit, id=habit_id, user=request.user)
    if request.method == 'POST':
        form = HabitNoteForm(request.POST, request.FILES)
        if form.is_valid():
            note = form.save(commit=False)
            note.habit = habit
            note.save()
            return redirect('habit_notes:all_notes')
    else:
        form = HabitNoteForm()
    return render(request, 'habit_notes/note_form.html', {'form': form, 'habit': habit})

def delete_note(request, note_id):
    note = get_object_or_404(HabitNote, id=note_id)
    
    # Проверяем, принадлежит ли заметка текущему пользователю
    if note.habit.user != request.user:
        return redirect('habit_notes:all_notes')

    if request.method == 'POST':
        note.delete()
        return redirect('habit_notes:all_notes')
    
    # Обработка GET-запросов
    return redirect('habit_notes:all_notes') 

habit_notes/templates/habit_notes/all_notes.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Notes all</title>
  <link rel="stylesheet" href="{%static 'css/styles_all_notes.css'%}">
</head>
<body>
<div class="wrapper">
  <header class="container">
    <nav>
        <ul class="left-nav">
            <li class="profile"><a href="{%url 'users:profile'%}" id="profile-button" >Profile</a></li>
            <li><a href="{%url 'habits:habit_list'%}" id="habits-button" >Habits</a></li>
            <li><a href="{%url 'habit_notes:all_notes'%}" id="diagrams-button" class="active">Notes</a></li>
        </ul>
        <span class="logo" id="home-button" ><a href="{%url 'main:main_after_registration'%}">HabitFlow </a></span>
        <ul class="right-nav">
            <li><a href="{%url 'main:settings'%}" id="settings-button">Settings</a></li>
            <li class="About"><a href="{%url 'main:about'%}" >About</a></li>
        </ul>
    </nav>
  </header>
</div>

<div class="wrapper_2">
    <div class="container_2">
{% for habit in habits %}
  <div style="margin-bottom: 40px;">
    <h1>{{ habit.name }} ({{ habit.get_category_display }})</small></h1>

    <a href="{% url 'habit_notes:add_note' habit.id %}" class="add-note">➕ Add a note</a>

  {% for note in habit.notes.all %}
  <div style="margin-top: 15px; padding: 10px; border: 1px solid #ddd;">
    <strong>{{ note.date }}</strong> — {{ note.get_mood_display }}
    <button class="delete-note-button" onclick="openNoteModal({{ note.id }})">🗑️</button>

    {% if note.photo %}
  <div class="image-preview">
    <img src="{{ note.photo.url }}" alt="Note Photo" class="thumbnail" onclick="openImageModal('{{ note.photo.url }}')">
  </div>
{% endif %}

    <p>{{ note.note }}</p>

    <div id="noteModal-{{ note.id }}" class="modal-overlay" style="display: none;">
      <div class="modal-content">
        <h3>Delete the note?</h3>
        <p>Note from <strong>{{ note.date }}</strong> will be deleted. Continue?</p>
        <form action="{% url 'habit_notes:delete_note' note.id %}" method="post">
          {% csrf_token %}
          <div class="modal-buttons">
            <button type="submit" class="confirm-button">Yes, delete</button>
            <button type="button" class="cancel-button" onclick="closeNoteModal({{ note.id }})">Cancel</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endfor %}{% endfor %}

</div>

<div id="imageModal" class="modal-overlay" style="display: none;">
    <div class="modal-content" style="background: none; box-shadow: none; padding: 0;">
      <img id="fullImage" src="" style="max-width: 90vw; max-height: 90vh; border-radius: 10px;">
    </div>
  </div>
  

<style>
    .thumbnail {
        width: 120px;
        height: auto;
        border-radius: 5px;
        cursor: pointer;
        transition: transform 0.2s ease;
      }
      
      .thumbnail:hover {
        transform: scale(1.05);
      }
      
      .image-preview {
        margin: 10px 0;
        text-align: left;
      }
      
      #imageModal .modal-content {
        display: flex;
        justify-content: center;
        align-items: center;
      }
      
    .modal-overlay {
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      background: rgba(0, 0, 0, 0.5);
      display: none;
      justify-content: center;
      align-items: center;
      z-index: 1000;
  }
  
  .modal-content {
      background:rgb(75, 78, 56);
      padding: 40px;
      border-radius: 20px;
      width: 450px;
      max-width: 90%;
      text-align: center;
  }
  
  .modal-content h3 {
      color: rgb(255, 255, 255);
      margin-bottom: 20px;
      font-size: 1.5rem;
      text-align: center;
  }
  
  .modal-content p {
      color: white;
      margin-bottom: 30px;
      font-size: 1.1rem;
      line-height: 1.5;
      text-align: center;
  }
  
  .modal-buttons {
      display: flex;
      justify-content: center;
      gap: 20px;
      margin-top: 30px;
  }
  
  .modal-buttons button {
      min-width: 120px;
      padding: 12px 25px;
      border-radius: 8px;
      font-weight: 600;
      cursor: pointer;
      border: none;
      transition: all 0.3s ease;
  }
  
  .confirm-button {
      background: #E3CDBB;
      color: #2f0f05;
  }
  
  .confirm-button:hover {
      background: #d4bda9;
  }
  
  .cancel-button {
      background: #383A2B;
      color: white;
  }
  
  .cancel-button:hover {
      background: #2a2c20;
  }
  </style>
  
<script>
    function openImageModal(imageUrl) {
        const modal = document.getElementById('imageModal');
        const img = document.getElementById('fullImage');
        img.src = imageUrl;
        modal.style.display = 'flex';
      }
      
      window.onclick = function(event) {
        if (event.target === document.getElementById('imageModal')) {
          document.getElementById('imageModal').style.display = 'none';
        }
      
        // Закрытие других модалок
        document.querySelectorAll('.modal-overlay').forEach(modal => {
          if (event.target === modal && modal.id !== 'imageModal') {
            modal.style.display = 'none';
          }
        });
      };
      
    function openNoteModal(noteId) {
      document.getElementById(`noteModal-${noteId}`).style.display = 'flex';
    }
  
    function closeNoteModal(noteId) {
      document.getElementById(`noteModal-${noteId}`).style.display = 'none';
    }
  
    window.onclick = function(event) {
      document.querySelectorAll('.modal-overlay').forEach(modal => {
        if (event.target === modal) {
          modal.style.display = 'none';
        }
      });
    };
  </script>
  
</body>
</html>

habit_notes/templates/habit_notes/note_form.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Add note</title>
    <link rel="stylesheet" href="{% static 'css/styles_note_form.css' %}">
</head>

<body>
    <div class="container">
        <h2>Add note to habit: {{ habit.name }}</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="input-group">
                <label for="id_date">Date:</label>
                <input type="date" class="form-control" id="id_date" 
                value="{% if form.date.value %}{{ form.date.value }}{% endif %}"
                name="date"
                required>
            </div>
            
            <div class="input-group">
                <label for="note">Note:</label>
                <textarea id="note"
                value="{% if form.note.value %}{{ form.note.value }}{% endif %}"
                name="note" 
                placeholder="Enter a note" 
                required></textarea>
            </div>

            <div class="input-group">
                <label for="photo">Photo:</label>
            
                <input type="file" id="photo" name="photo" accept="image/*" class="file-input">
                <label for="photo" class="file-button">Add file</label>
                <span id="file-name" class="file-name">No file selected</span>
              </div>

            <div class="input-group">
                <label for="mood">Mood:</label>
                <select id="mood" 
                name="mood" 
                value="{% if form.mood.value %}{{ form.mood.value }}{% endif %}"
                placeholder="Choose mood" 
                required>
                    <option value="" disabled selected></option>
                    <option value="happy">😊 Happy</option>
                    <option value="neutral">😐 Neutral</option>
                    <option value="sad">😞 Sad</option>
                    <option value="angry">😠 Angry</option>
                    <option value="tired">😩 Tired</option>
                </select>
            </div>

            <button type="submit">Save</button>
        </form>
        <a class="back-link" href="{% url 'habit_notes:all_notes'%}">← Back to notes</a>
    </div>
    <style>
        .file-input {
            display: none;
          }
          
          .file-button {
            display: inline-block;
            background-color: #5c2b0d;
            color: white;
            padding: 10px 25px;
            border-radius: 8px;
            cursor: pointer;
            text-align: center;
            font-weight: bold;
          }
          
          .file-button:hover {
            background-color: #421f08;
          }
          
          .file-name {
            margin-left: 15px;
            font-style: italic;
            color: #666;
          }
          
    </style>
    <script>
        const fileInput = document.getElementById("photo");
        const fileNameSpan = document.getElementById("file-name");
      
        fileInput.addEventListener("change", function () {
          if (fileInput.files.length > 0) {
            fileNameSpan.textContent = fileInput.files[0].name;
          } else {
            fileNameSpan.textContent = "No file selected";
          }
        });
      </script>
      
    </body>
    </html>