habit_notes/urls.py
from django.urls import path
from . import views

app_name = 'habit_notes'

urlpatterns = [
    path('', views.all_notes_view, name='all_notes'),
    path('habit/<int:habit_id>/notes/add/', views.add_note, name='add_note'),
    path('note/<int:note_id>/delete/', views.delete_note, name='delete_note'), 
]

habitflow/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('habits/', include('habits.urls', namespace='habits')),
    path('notes/', include('habit_notes.urls', namespace='habit_notes')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

habits/urls.py
# habits/urls.py
from django.urls import path
from . import views

app_name = 'habits'

urlpatterns = [
    path('create/', views.create_habit, name='create_habit'),
    path('your_habits/', views.habit_list, name='habit_list'),
    path('tracker/<int:habit_id>/', views.habit_tracker_view, name='habit_tracker'),
    path('tracker/<int:habit_id>/toggle/', views.toggle_completion, name='toggle_completion'),
    path('delete/<int:habit_id>/', views.delete_habit, name='delete_habit'),
]

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name= 'index'),
    path('about/', views.about, name= 'about'),
    path('about_us/', views.about_us, name= 'about_us'),
    path('settings/', views.settings, name= 'settings'),
    path('main-after-registration/', views.main_after_registration, name='main_after_registration'),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name= 'login'),
    path('registration/', views.registration, name= 'registration'),
    path('profile/', views.profile, name= 'profile'),
    path(
        'password_reset/',
        auth_views.PasswordResetView.as_view(
            template_name='users/password_reset_form.html',
            email_template_name='users/password_reset_email.html',
            subject_template_name='users/password_reset_subject.txt',
            success_url='done/'
        ),
        name='password_reset'
    ),
    
    path(
        'password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url='/users/reset/done/'
        ),
        name='password_reset_confirm'
    ),

    path(
        'reset/done/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),

    path('logout/', views.logout, name= 'logout'),
    path('delete_account/', views.delete_account, name='delete_account'),
]

habits/models.py
from django.db import models
from django.conf import settings

class Habit(models.Model):
    GOOD_OR_BAD_CHOICES = (
        ('good', 'Good'),
        ('bad', 'Bad'),
    )

    FREQUENCY_CHOICES = (
        ('daily', 'Daily'),
        ('weekly', 'Weekly'),
        ('biweekly', 'Every 2 Weeks'),
        ('monthly', 'Monthly'),
        ('semiannual', 'Every 6 Months'),
        ('yearly', 'Yearly'),
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='habits'
    )
    
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    category = models.CharField(max_length=4, choices=GOOD_OR_BAD_CHOICES)
    frequency = models.CharField(max_length=10, choices=FREQUENCY_CHOICES)
    end_date = models.DateField()
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f'{self.name} ({self.category})'
    

class HabitCompletion(models.Model):
    habit = models.ForeignKey(Habit, on_delete=models.CASCADE, related_name='completions')
    date = models.DateField()
    completed = models.BooleanField(default=False)

    class Meta:
        unique_together = ('habit', 'date')
    
    def __str__(self):
        return f'Habit: {self.habit.name} | {self.date} | Completed: {self.completed}'


        

habits/forms.py
from django import forms
from .models import Habit

class HabitForm(forms.ModelForm):

    name = forms.CharField()
    description = forms.CharField()
    category = forms.CharField()
    frequency = forms.CharField()
    end_date = forms.CharField()
    
    class Meta:
        model = Habit
        fields = ['name', 'description', 'category', 'frequency', 'end_date']

habits/views.py
from django.shortcuts import render, redirect
from .forms import HabitForm
from .models import Habit, HabitCompletion
from django.shortcuts import get_object_or_404, render
from datetime import timedelta
import json
from django.http import JsonResponse, HttpResponse
from django.views.decorators.http import require_POST
from django.utils.dateparse import parse_date


def create_habit(request):
    if request.method == 'POST':
        form = HabitForm(request.POST)
        if form.is_valid():
            habit = form.save(commit=False)
            habit.user = request.user  
            habit.save()
            return redirect('habits:habit_list')  
    else:
        form = HabitForm()
    
    return render(request, 'habits/add_habitat.html', {'form': form})

def habit_list(request):
    habits = Habit.objects.filter(user=request.user)

    if(habits): return render(request, 'habits/list_habitats.html', {'habits': habits})
    else: return render(request, 'habits/habitat_without_value.html')

def habit_tracker_view(request, habit_id):
    habit = get_object_or_404(Habit, pk=habit_id, user=request.user)

    start_date = habit.created_at.date()  
    end_date = habit.end_date

    dates_list = generate_date_points(start_date, end_date, habit.frequency)

    completions = habit.completions.filter(date__in=dates_list, completed=True)
    completed_dates = set(c.date for c in completions)

    context = {
        'habit': habit,
        'dates_list': dates_list,  
        'completed_dates': completed_dates,
    }
    return render(request, 'habits/habit_tracker.html', context)


def generate_date_points(start_date, end_date, frequency):

    result = []
    delta_map = {
        'daily': 1,
        'weekly': 7,
        'biweekly': 14,
        'monthly': 30,
        'semiannual': 180,
        'yearly': 365,
    }

    step = delta_map.get(habit_frequency_key(frequency), 1)
    
    current = start_date
    while current <= end_date:
        result.append(current)
        current += timedelta(days=step)
    
    return result


def habit_frequency_key(frequency):
    return frequency.lower()

@require_POST 
def toggle_completion(request, habit_id):
    if request.method == 'POST':
        user = request.user
        habit = get_object_or_404(Habit, pk=habit_id, user=user)

        data = json.loads(request.body.decode('utf-8'))
        date_str = data.get('date')
        completed = data.get('completed', False)

        date_obj = parse_date(date_str) 
        
        if not date_obj:
            return JsonResponse({'success': False, 'error': 'Invalid date'}, status=400)
        
       
        completion, created = HabitCompletion.objects.get_or_create(
            habit=habit, date=date_obj
        )
        completion.completed = completed
        completion.save()

        return JsonResponse({'success': True})
    
    return JsonResponse({'success': False, 'error': 'Invalid request method'}, status=405)


def delete_habit(request, habit_id):
    habit = get_object_or_404(Habit, id=habit_id, user=request.user)
    if request.method == 'POST':
        habit.delete()
        return redirect('habits:habit_list')
    return HttpResponse("This page is only for POST requests", status=400)

habits/templates/habits/add_habitat.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Habit</title>
    <link rel="stylesheet" href="{% static 'css/style_add_habitat.css'%}">
</head>
<body>
<div class="wrapper">
    <header class="container_1">
        <nav>
          <ul class="left-nav">
            <li class="profile"><a href="{%url 'users:profile'%}" id="profile-button" >Profile</a></li>
            <li><a href="{%url 'habits:habit_list'%}" id="habits-button" class="active">Habits</a></li>
            <li><a href="{%url 'habit_notes:all_notes'%}" id="diagrams-button">Notes</a></li>
        </ul>
        <span class="logo" id="home-button" ><a href="{%url 'main:main_after_registration'%}">HabitFlow </a></span>
        <ul class="right-nav">
            <li><a href="{%url 'main:settings'%}" id="settings-button">Settings</a></li>
            <li class="About"><a href="{%url 'main:about'%}" >About</a></li>
        </ul>
        </nav>
    </header>
</div>

<div class="container_2"> 
    <div class="content">

        <div class="form-section">
        <!-- Форма отправляется по адресу `habits:create_habit` методом POST -->
        <form action="{% url 'habits:create_habit' %}" method="post">
            {% csrf_token %}
            
            <!-- Name -->
            <input type="text" class="form-control" id="id_name"
                   value="{% if form.name.value %}{{ form.name.value }}{% endif %}"
                   name="name"
                   placeholder="Name of habit" required>
            {% if form.name.errors %}
              <div class="alert alert-danger alert-dismissible fade show">
                {{ form.name.errors }}
              </div>
            {% endif %}

            <!-- Description -->
            <input type="text" class="form-control" id="id_description"
                   value="{% if form.description.value %}{{ form.description.value }}{% endif %}"
                   name="description"
                   placeholder="Describe habit">
            {% if form.description.errors %}
              <div class="alert alert-danger alert-dismissible fade show">
                {{ form.description.errors }}
              </div>
            {% endif %}
            
            <!-- Category -->
            <select class="form-control" id="id_category" name="category" required>
                <!-- Для "placeholder"-опции -->
                <option value="" disabled selected hidden>Category</option>
                <option value="good">Good</option>
                <option value="bad">Bad</option>
            </select>
            {% if form.category.errors %}
              <div class="alert alert-danger alert-dismissible fade show">
                {{ form.category.errors }}
              </div>
            {% endif %}
            
            <!-- Frequency -->
            <select class="form-control" id="id_frequency" name="frequency" required>
                <option value="" disabled selected hidden>Frequency of execution</option>
                <option value="daily">Daily</option>
                <option value="weekly">Weekly</option>
                <option value="biweekly">Every 2 Weeks</option>
                <option value="monthly">Monthly</option>
                <option value="semiannual">Every 6 Months</option>
                <option value="yearly">Yearly</option>
            </select>
            {% if form.frequency.errors %}
              <div class="alert alert-danger alert-dismissible fade show">
                {{ form.frequency.errors }}
              </div>
            {% endif %}
            
            <!-- End Date -->
            <input type="text" class="form-control" id="id_end_date"
                   value="{% if form.end_date.value %}{{ form.end_date.value }}{% endif %}"
                   name="end_date"
                   placeholder="End Date"
                   onfocus="(this.type='date')"
                   onblur="if(!this.value) this.type='text'"
                   required>
            {% if form.end_date.errors %}
              <div class="alert alert-danger alert-dismissible fade show">
                {{ form.end_date.errors }}
              </div>
            {% endif %}
            
            <!-- Кнопка добавления -->
            <button type="submit" class="add-button">Add</button>
        </form>
    </div>
    </div>
    
    <!-- Картинка  -->
    <div class="image-section">
        <img src="{% static 'img/habitat_img.svg'%}" alt="Meditation Illustration">
    </div>
</div>

</body>
</html>

habits/templates/habits/habit_tracker.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>{{ habit.name }} Tracker</title>
  <link rel="stylesheet" href="{% static 'css/style_habit_tracker.css' %}">
</head>
<body>
<div class="container_2">
  <h1>{{ habit.name }}</h1>
  <p>From {{ habit.get_start_date }} to {{ habit.end_date }} | Frequency: {{ habit.frequency }}</p>
  <p>{{ habit.description }}</p>

  <div class="habit-tracker">
    {% for day_date in dates_list %}
      {% if day_date in completed_dates %}
        <div 
          class="tracker-circle completed" 
          data-date="{{ day_date|date:'Y-m-d' }}">
        </div>
      {% else %}
        <div 
          class="tracker-circle"
          data-date="{{ day_date|date:'Y-m-d' }}">
        </div>
      {% endif %}
    {% endfor %}
  </div>

  <a href="{% url 'habits:habit_list' %}" class="back-button">Back to List</a>
</div>

{% csrf_token %}
<script>
document.addEventListener("DOMContentLoaded", function() {
  
  document.querySelectorAll('.tracker-circle').forEach(function(circle) {
    circle.addEventListener('click', function() {
      const circleElem = this;
      const dateValue = circleElem.getAttribute('data-date');

      const willBeCompleted = !circleElem.classList.contains('completed');

      fetch("{% url 'habits:toggle_completion' habit.id %}", {
        method: "POST",
        headers: {
          "X-CSRFToken": "{{ csrf_token }}",
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          date: dateValue,
          completed: willBeCompleted
        })
      })
      .then(response => response.json())
      .then(data => {
        if (data.success) {
          circleElem.classList.toggle('completed');
        } else {
          alert(data.error);
        }
      })
      .catch(err => console.error('Error:', err));
    });
  });
});
</script>

</body>
</html>

habits/templates/habits/habitat_without_value.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Habits without value</title>
  <link rel="stylesheet" href="{% static 'css/style_habitat_without_value.css'%}">
</head>
<body>
<div class="wrapper">
  <header class="container_1">
    <nav>
      <ul class="left-nav">
        <li class="profile"><a href="{%url 'users:profile'%}" id="profile-button" >Profile</a></li>
        <li><a href="{%url 'habits:habit_list'%}" id="habits-button" class="active">Habits</a></li>
        <li><a href="{%url 'habit_notes:all_notes'%}" id="diagrams-button">Notes</a></li>
    </ul>
    <span class="logo" id="home-button" ><a href="{%url 'main:main_after_registration'%}">HabitFlow </a></span>
    <ul class="right-nav">
        <li><a href="{%url 'main:settings'%}" id="settings-button">Settings</a></li>
        <li class="About"><a href="{%url 'main:about'%}" >About</a></li>
    </ul>
    </nav>
  </header>
</div>
<div class="container_2">
  <h1>You don't have any habits right now!</h1>
  <h2>Add them now!</h2>
  <button class="add-habit" onclick="window.location.href='{% url 'habits:create_habit' %}'">
    Add habit
  </button>


</div>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
html, body {
    margin: 0;
    padding: 0;
    width: 100vw;
    height: 100%;
}
body {
    display: flex;
    flex-direction: column;
    background: #F0E4DF;
    font-family: "Poppins", serif;
    font-weight: 600;
}

a {
    text-decoration: none; /* Убираем стандартное подчеркивание */
    color: #000000; /* Цвет текста */
    position: relative; /* Нужно для псевдоэлемента */
}

/* Подчеркивание при наведении */
a:hover::after {
    content: "";
    position: absolute;
    left: 0;
    bottom: -2px; /* Расстояние от текста */
    width: 100%;
    height: 2px; /* Толщина подчеркивания */
    background-color: #2f0f05; /* Бежевый цвет подчеркивания */
}
.left-nav a {
    text-decoration: none; /* Убираем стандартное подчеркивание */
    color: #000; /* Цвет текста */
    position: relative;
}

/* Подчеркивание при наведении */
.left-nav a:hover::after {
    content: "";
    position: absolute;
    left: 0;
    bottom: -2px;
    width: 100%;
    height: 2px;
    background-color: #2f0f05; /* Бежевый цвет */
}

/* Подчеркивание активной кнопки */
.left-nav a.active::after {
    content: "";
    position: absolute;
    left: 0;
    bottom: -2px;
    width: 100%;
    height: 2px;
    background-color: #2f0f05; /* Бежевый цвет */
}

/* Всегда подчеркнута */
.about::after {
    content: "";
    position: absolute;
    left: 0;
    bottom: -2px;
    width: 100%;
    height: 2px;
    background-color: #2f0f05; /* Цвет подчеркивания */
}

.wrapper {
    background-color: #F0E4DF;
    width: 100vw;
    margin: 0;
    padding: 0;
}

.container_1 {
    width: 1400px;
    margin: 0 auto;
    padding: 0;
    color: #2f0f05;
}

header {
    padding: 50px 0;
}

header nav {
    display: flex;
    align-items: center;
    justify-content: space-between;
}

header .left-nav,
header .right-nav {
    list-style: none;
    display: flex;
    gap: 20px;
}

header .left-nav {
    flex: 1;
    justify-content: flex-start;
    margin-left: -50px; /* Регулируйте значение, чтобы сместить левее */
}

header .right-nav {
    flex: 1;
    justify-content: flex-end;
}
.container_2 {
    color: #2f0f05;
    background: #ffffff;
    width: 100vw;
    height: 70vh;
    max-width: 1400px;
    margin: 10px auto;
    padding: 40px;
    border-radius: 20px;
}

/* Текст */
.container_2 h1 {
    margin-top: 150px;
    margin-left: 400px;
    color: #000;
    font-weight: 500;
    margin-bottom: 10px;
}
.container_2 h2 {
    margin-left: 600px;
    color: #000;
    font-weight: 500;
    margin-bottom: 10px;
}

    /* Кнопка */
.add-habit {
    background-color: #5E2611;
    color: white; /* Делаем текст белым */
    padding: 15px 80px;
    border: none;
    border-radius: 20px;
    font-size: 1.2rem;
    cursor: pointer;
    margin-top: 20px;
    margin-left: 570px;
    text-decoration: none; /* Убираем подчеркивание */
    display: inline-block;
}

.add-habit:hover {
    background-color: #9f3f20;
}

/* Если все-таки используется <a> внутри кнопки */
.add-habit a {
    color: white; /* Делаем текст белым */
    text-decoration: none; /* Убираем подчеркивание */
    display: block;
    width: 100%;
    height: 100%;
}

</style>
</body>
</html>

habits/templates/habits/list_habitats.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>List of Habits</title>
  <link rel="stylesheet" href="{% static 'css/style_list_habitats.css' %}">
</head>
<body>
<div class="wrapper">
  <header class="container_1">
    <nav>
      <ul class="left-nav">
        <li class="profile"><a href="{%url 'users:profile'%}" id="profile-button" >Profile</a></li>
        <li><a href="{%url 'habits:habit_list'%}" id="habits-button" class="active">Habits</a></li>
        <li><a href="{%url 'habit_notes:all_notes'%}" id="diagrams-button">Notes</a></li>
    </ul>
    <span class="logo" id="home-button" ><a href="{%url 'main:main_after_registration'%}">HabitFlow </a></span>
    <ul class="right-nav">
        <li><a href="{%url 'main:settings'%}" id="settings-button">Settings</a></li>
        <li class="About"><a href="{%url 'main:about'%}" >About</a></li>
    </ul>
    </nav>
  </header>
</div>

<div class="container_2">
  <div class="content">
    <div class="habit-list-section">
      <h2>List your habits</h2>
      <ul>
        {% for habit in habits %}
    <li>
      <a href="{% url 'habits:habit_tracker' habit.id %}">
        {{ habit.name }}
      </a>
      <button class="delete-btn" onclick="openDeleteModal({{ habit.id }}, '{{ habit.name }}')">🗑️</button>
      <br>
      {{ habit.description }}


  </li>
  {% endfor %}
      </ul>
      <button class="add-button" onclick="window.location.href='{% url 'habits:create_habit' %}'">
        Add habit
      </button>
    </div>
    <div class="image-section">
      <img src="{% static 'img/habits_list_img.svg' %}" alt="Habit Illustration">
    </div>
  </div>
</div>

<div id="deleteModal" class="modal-overlay" style="display: none;">
  <div class="modal-content">
    <h3>Delete Habit</h3>
    <p id="habit-delete-text">Are you sure you want to delete this habit?</p>
    <form id="deleteHabitForm" method="post">
      {% csrf_token %}
      <div class="modal-buttons">
        <button type="submit" class="confirm-button">Yes, delete</button>
        <button type="button" class="cancel-button" onclick="closeModal()">Cancel</button>
      </div>
    </form>
  </div>
</div>

<style>
  .modal-overlay {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: rgba(0, 0, 0, 0.5);
    display: none;
    justify-content: center;
    align-items: center;
    z-index: 1000;
}

.modal-content {
    background:rgb(75, 78, 56);
    padding: 40px;
    border-radius: 20px;
    width: 450px;
    max-width: 90%;
    text-align: center;
}

.modal-content h3 {
    color: rgb(255, 255, 255);
    margin-bottom: 20px;
    font-size: 1.5rem;
    text-align: center;
}

.modal-content p {
    color: white;
    margin-bottom: 30px;
    font-size: 1.1rem;
    line-height: 1.5;
    text-align: center;
}

.modal-buttons {
    display: flex;
    justify-content: center;
    gap: 20px;
    margin-top: 30px;
}

.modal-buttons button {
    min-width: 120px;
    padding: 12px 25px;
    border-radius: 8px;
    font-weight: 600;
    cursor: pointer;
    border: none;
    transition: all 0.3s ease;
}

.confirm-button {
    background: #E3CDBB;
    color: #2f0f05;
}

.confirm-button:hover {
    background: #d4bda9;
}

.cancel-button {
    background: #383A2B;
    color: white;
}

.cancel-button:hover {
    background: #2a2c20;
}
</style>

<script>
  function openDeleteModal(habitId, habitName) {
    const modal = document.getElementById('deleteModal');
    const form = document.getElementById('deleteHabitForm');
    const text = document.getElementById('habit-delete-text');
    form.action = `/habits/delete/${habitId}/`; // ⚠️ Убедись, что такой путь есть в urls.py
    text.innerText = `Are you sure you want to delete the habit "${habitName}"?`;
    modal.style.display = 'flex';
  }

  function closeModal() {
    document.getElementById('deleteModal').style.display = 'none';
  }

  window.onclick = function(event) {
    const modal = document.getElementById('deleteModal');
    if (event.target === modal) {
      closeModal();
    }
  }
</script>


</body>
</html>