habit_notes/urls.py
from django.urls import path
from . import views

app_name = 'habit_notes'

urlpatterns = [
    path('', views.all_notes_view, name='all_notes'),
    path('habit/<int:habit_id>/notes/add/', views.add_note, name='add_note'),
    path('note/<int:note_id>/delete/', views.delete_note, name='delete_note'), 
]

habitflow/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('users/', include('users.urls', namespace='users')),
    path('habits/', include('habits.urls', namespace='habits')),
    path('notes/', include('habit_notes.urls', namespace='habit_notes')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

habits/urls.py
# habits/urls.py
from django.urls import path
from . import views

app_name = 'habits'

urlpatterns = [
    path('create/', views.create_habit, name='create_habit'),
    path('your_habits/', views.habit_list, name='habit_list'),
    path('tracker/<int:habit_id>/', views.habit_tracker_view, name='habit_tracker'),
    path('tracker/<int:habit_id>/toggle/', views.toggle_completion, name='toggle_completion'),
    path('delete/<int:habit_id>/', views.delete_habit, name='delete_habit'),
]

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name= 'index'),
    path('about/', views.about, name= 'about'),
    path('about_us/', views.about_us, name= 'about_us'),
    path('settings/', views.settings, name= 'settings'),
    path('main-after-registration/', views.main_after_registration, name='main_after_registration'),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name= 'login'),
    path('registration/', views.registration, name= 'registration'),
    path('profile/', views.profile, name= 'profile'),
    path(
        'password_reset/',
        auth_views.PasswordResetView.as_view(
            template_name='users/password_reset_form.html',
            email_template_name='users/password_reset_email.html',
            subject_template_name='users/password_reset_subject.txt',
            success_url='done/'
        ),
        name='password_reset'
    ),
    
    path(
        'password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url='/users/reset/done/'
        ),
        name='password_reset_confirm'
    ),

    path(
        'reset/done/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),

    path('logout/', views.logout, name= 'logout'),
    path('delete_account/', views.delete_account, name='delete_account'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import BaseUserManager


class User(AbstractUser):
    
    email = models.EmailField(unique=True)

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'
        ordering = ['last_name', 'first_name']

    def get_display_name(self):
        full_name = self.get_full_name().strip()
        return full_name if full_name else self.username
    
    def __str__(self):
        return f'{self.get_full_name()} ({self.email})'

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from .models import User

class UserRegisterForm(UserCreationForm):
    
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']
        
    # def clean_password2(self):

    #     password1 = self.cleaned_data.get("password1")
    #     password2 = self.cleaned_data.get("password2")
        
    #     if password1 and password2 and password1 != password2:
    #         raise ValidationError("Passwords don't match")
    #     return password2
    


class UserLoginForm(AuthenticationForm):

    username = forms.CharField()
    password = forms.CharField()
    
    # error_messages = {
    #     'invalid_login': "Invalid email or password",
    #     'inactive': "This account is inactive.",
    # }

    class Meta:
        model = User
        fields = ['username', 'password']

class ForgotPasswordForm(forms.Form):
    username = forms.CharField(
        label='Имя пользователя',
        max_length=150,
        required=True
    )
    new_password = forms.CharField(
        label='Новый пароль',
        widget=forms.PasswordInput,
        min_length=8,
        required=True
    )

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages, auth
from django.urls import reverse
from django.http import HttpResponseRedirect
from .forms import UserLoginForm, UserRegisterForm
from habits.models import Habit

def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username = username, password=password)

            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('main:main_after_registration'))
    else:
        form = UserLoginForm()
    return render(request, 'users/registration.html', {'form': form})

def registration(request):
    if request.method == 'POST':
        form = UserRegisterForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:login'))
    else:
        form = UserRegisterForm()
    return render(request, "users/registr.html", {'form': form})


def profile(request):
    habits = Habit.objects.filter(user=request.user)
    context = {
        'user': request.user,
        'habits': habits
    }
    return render(request, "users/profile.html", context)

def logout(request):
    auth.logout(request)
    return redirect('main:index')

def delete_account(request):
    if request.method == 'POST':
        user = request.user
        auth.logout(request)           
        user.delete()            
        return redirect('main:index')  
    return redirect('main:settings')  

users/templates/users/password_reset_complete.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>note_password</title>
  <link rel="stylesheet" href="{% static 'css/style_note_changed_password.css' %}">
</head>
<body>
<div class="container">
  <div class="text">
    <h1>Password successfully changed.</h1>
    <p>You can now <a href="{% url 'users:login' %}">log in</a>  with your new password.</p>
  </div>
</div>
</body>

users/templates/users/password_reset_confirm.html
{% load static %}

  <!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reset Password</title>
    <link rel="stylesheet" href="{% static 'css/styless_forgot_password.css' %}">
  </head>
  <body>
  <div class="container">
    <div class="card">
      <div class="left-side">
        <div class="illustration_fon">
          <img src="{% static 'img/fon_illustation_for_registration.svg' %}" alt="Background Illustration">
        </div>
        <div class="illustration">
          <img src="{% static 'img/img_register.svg' %}" alt="Main Illustration">
        </div>
      </div>
      <div class="right-side">
        <h1>Reset password</h1>
  
        <form method="post">
          {% csrf_token %}

          <label for="id_password1" class="form-label">New password</label>
            <input type="password" class="form-control" id="id_password1"
            value="{% if form.new_password1.value %}{{ form.new_password1.value }}{% endif %}"
            name="new_password1"
            placeholder="Enter your new password" required>
            {% if form.new_password1.errors %}
            <div class="alert alert-danger alert-dismissible fade show">{{form.new_password1.errors}}</div>
            {% endif %}

            <label for="id_password2" class="form-label">Confirm password</label>
            <input type="password" class="form-control" id="id_password2"
            value="{% if form.new_password2.value %}{{ form.new_password2.value }}{% endif %}"
            name="new_password2"
            placeholder="Confirm your password" required>
            {% if form.new_password2.errors %}
            <div class="alert alert-danger alert-dismissible fade show">{{form.new_password2.errors}}</div>
            {% endif %}

          <button type="submit" class="reset">Reset Password</button>
        </form>
      </div>
    </div>
  </div>
  </body>
  </html>
  

users/templates/users/password_reset_done.html
{% load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>note_password</title>
    <link rel="stylesheet" href="{% static 'css/style_note_password_email.css' %}">
</head>
<body>
<div class="container">
    <div class="text">
        <h1>We sent you a letter.</h1>
        <p>Check your email and follow the link to change your password.</p>
    </div>
</div>
</body>

users/templates/users/password_reset_email.html
Здравствуйте!

Вы запросили сброс пароля на сайте "HabitFlow".

Чтобы установить новый пароль, нажмите на ссылку:
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

Если вы не запрашивали сброс пароля, просто проигнорируйте это письмо.

users/templates/users/password_reset_form.html
{% load static %}

  <!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reset Password</title>
    <link rel="stylesheet" href="{% static 'css/styless_forgot_password.css' %}">
  </head>
  <body>
  <div class="container">
    <div class="card">
      <div class="left-side">
        <div class="illustration_fon">
          <img src="{% static 'img/fon_illustation_for_registration.svg' %}" alt="Background Illustration">
        </div>
        <div class="illustration">
          <img src="{% static 'img/img_register.svg' %}" alt="Main Illustration">
        </div>
      </div>
      <div class="right-side">
        <h1>Reset password</h1>
  
        <form action = {% url 'users:password_reset' %} method="post">
          {% csrf_token %}

          <label for="reset-email" class="form-label">Enter your email address so that we can send you the email to change your password</label>
          <input type="email" class="form-control" id="reset-email" 
          value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
          name="email"
          placeholder="Enter your email address" required>
          {% if form.email.errors %}
          <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
          {% endif %}

          <button type="submit" class="reset">Sent the email</button>
        </form>
        <a href="{% url 'users:login' %}" class="back-to-login">Back to Login</a>
      </div>
    </div>
  </div>
  </body>
  </html>
  

users/templates/users/profile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Profile Page</title>
  <link rel="stylesheet" href="{% static 'css/styles_profile.css' %}">
</head>
<body>
<div class="wrapper">
  <header class="container_1">
    <nav>
      <ul class="left-nav">
        <li class="profile"><a href="{%url 'users:profile'%}" id="profile-button" class="active">Profile</a></li>
        <li><a href="{%url 'habits:habit_list'%}" id="habits-button">Habits</a></li>
        <li><a href="{%url 'habit_notes:all_notes'%}" id="diagrams-button">Notes</a></li>
    </ul>
    <span class="logo" id="home-button" ><a href="{%url 'main:main_after_registration'%}">HabitFlow </a></span>
    <ul class="right-nav">
        <li><a href="{%url 'main:settings'%}" id="settings-button">Settings</a></li>
        <li class="About"><a href="{%url 'main:about'%}" >About</a></li>
    </ul>
    </nav>
  </header>
</div>

<!-- Основное содержимое -->
<div class="container_2">
  <div class="content">
    <div class="text-section">
      <h1 id="profile-greeting">Hello, {{ user.get_display_name }}</h1>
      <h2>Your habits:</h2>
      {% if habits %}
      <ul class="habit-list">
      {% for habit in habits %}
        <li>
          <strong>{{ habit.name }}</strong><br>
          <span>{{ habit.description }}</span>
        </li>
      {% endfor %}
    </ul>
     {% else %}
    <p id="no-habits-message">You don't have any habits yet, add them!</p>
    {% endif %}
      <button id="add-habit-btn" onclick="window.location.href='{% url 'habits:create_habit' %}'">
        Add habit
      </button>
    </div>
    <div class="image-section">
      <img src="{% static 'img/profile.svg'%}" alt="">
    </div>
  </div>
  <p class="motivation-text">Achieve your goals and become the best version of yourself!</p>
</div>
<style>
  .container_2 {
    color: #2f0f05;
    background: #ffffff;
    width: 100%;
    max-width: 1400px;
    margin: 10px auto;
    padding: 40px;
    border-radius: 20px;
}
</style>
</body>
</html>

users/templates/users/registr.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration</title>
    <link rel="stylesheet" href="{% static 'css/styles_registr.css' %}">
</head>
<body>
<div class="container">
    <div class="card">
        <h1>Registration</h1>
        <p>Please fill in the details to create an account.</p>
        <form action="{% url 'users:registration'%}"  method="post">
            {% csrf_token %}

            <label for="id_first_name" class="form-label">First Name</label>
            <input type="text" class="form-control" id="id_first_name" 
            value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
            name="first_name"
            placeholder="Enter your first name" required>
            {% if form.first_name.errors %}
            <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
            {% endif %}


            <label for="id_last_name" class="form-label">Last Name</label>
            <input type="text" class="form-control" id="id_last_name" 
            value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
            name="last_name"
            placeholder="Enter your last name" required>
            {% if form.last_name.errors %}
            <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
            {% endif %}

            <label for="id_username" class="form-label">Username</label>
            <input type="text" class="form-control" id="id_username"
            value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
            name="username"
            placeholder="Enter your username" required>
            {% if form.username.errors %}
            <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
            {% endif %}

            <label for="id_email" class="form-label">Email Address</label>
            <input type="email" class="form-control" id="id_email" 
            value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
            name="email"
            placeholder="Enter your email" required>
            {% if form.email.errors %}
            <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
            {% endif %}

            <label for="id_password1" class="form-label">Password</label>
            <input type="password" class="form-control" id="id_password1"
            value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}"
            name="password1"
            placeholder="Enter the password" required>
            {% if form.password1.errors %}
            <div class="alert alert-danger alert-dismissible fade show">{{form.password1.errors}}</divЩ>
            {% endif %}

            <label for="id_password2" class="form-label">Confirm Password</label>
            <input type="password" class="form-control" id="id_password2"
            value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}"
            name="password2"
            placeholder="Confirm your password" required>
            {% if form.password2.errors %}
            <div class="alert alert-danger alert-dismissible fade show">{{form.password2.errors}}</div>
            {% endif %}

            <button type="submit" class="register-button">Register</button>
        </form>
        <a href="{% url 'users:login' %}" class="back-to-login">Back to Login</a>
    </div>
</div>
</body>
</html>

users/templates/users/registration.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Page</title>
    <link rel="stylesheet" href="{% static 'css/styles_registration.css' %}">
</head>
<body>
<div class="container">
    <div class="card">
        <div class="left-side">
            <div class="illustration_fon">
                <img src="{% static 'img/fon_illustation_for_registration.svg'%}" alt="Background Illustration">
            </div>
            <div class="illustration">
                <img src="{% static 'img/img_register.svg'%}" alt="Main Illustration">
            </div>
        </div>
        <div class="right-side">
            <h1>Welcome Back!</h1>
            <p>Please login or register to continue</p>

            <!-- Форма входа -->
            <form action = "{% url "users:login" %}" method = "post">
                {% csrf_token %}
                {% if request.GET.next %}
                <input type="hidden" name="next" value={{request.GET.next}}>
                {% endif %}

                <label for="id_username" class="form-label">Username</label>
                <input type="text" class="form-control"
                value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                name="username" id="id_username"
                placeholder="Enter your username"
                required>

                <label for="login-password" class = "form-label">Password</label>
                <input type="password" class = "form-control"
                name = "password" id="login-password" 
                placeholder="Enter your password" 
                required>

                

                <a href="{% url 'users:password_reset'%}" class="forgot-password">Forgot password?</a>
                <br>
                <button type="submit" class="login">Login</button>
                <span class="or">or</span>
                <a href="{% url 'users:registration' %}" class="register">Register</a>

                
            </form>
        </div>
    </div>
</div>
<style>

    .login,
.register {
    background-color: #5E2611;
    color: white;
    padding: 10px 20px;
    width: 120px;
    height: 40px;
    display: inline-flex;
    justify-content: center;
    align-items: center;
    border: none;
    border-radius: 8px;
    font-size: 16px;
    text-decoration: none;
    box-sizing: border-box;
    margin-bottom: 10px;
    cursor: pointer;
}

.login:hover {
    background-color: #9f3f20;
}

.register:hover {
    background-color: #705d5c;
}

</style>
<script src="{% static 'script_registration.js' %}"></script>
</body>
</html>